### ISSUE TITLE
Need to handle log messages from Athanor library

### ISSUE THREAD

**Issue by andrewresearch** [uts-cic/athanor-server#25]

**Comment by josephharfouch** [comment]
I put some log messages into athanor library code and I could see them when I run sbt test. Could you please expand on what you mean by handling log messages. Are there log messages that you expect to see that are not coming out that I should investigate, or some test cases or scenarios where you expect an error message but that does not come out.

**Comment by josephharfouch** [comment]
I noticed looking at java/src/jatanor.cxx that some error messages that happen earlier during the load are diagnosed and logged to stderr by issuing cerr, however errors that happen during parsing such as during call to analyseJson are not logged but the returned Jsonstring returns the text of the error, such as "Unknown function" if I manually modify the name of the hardcoded Apply supplied function to a none existing function. The testcase would be pick this up as the returned value does not match the expected value but it is possible that code that is not checking for expected values wouldn't as it is not easy distinguished valid from error messages automatically. I am not sure if this is going off track or if it accounts for missing error messages, but I could add few log messages to athanor in java/src/cxx/jatanor.cxx to log these errors. It is not so easy to catch them in athanor-server.

**Comment by andrewresearch** [comment]
Perhaps we close this for now. It's possible that this issue was with an earlier version of athanor, because I don't think originally we were getting any log messages at all.
