### ISSUE TITLE
Endpoint to load grammar from ext url - GitHub

### ISSUE THREAD

**Issue by andrewresearch** [uts-cic/athanor-server#32]
Related to #27

**Comment by andrewresearch** [comment]
This can be implemented as a parameter e.g. 

```?grammar=analytic``` and ```?grammar=reflective```

**Comment by josephharfouch** [comment]
More details on this feature:
For the reflective option, we need to call "apply.kif". 
For the analytic option, we need to call "apply_ana.kif"

**Comment by andrewresearch** [comment]
Yes, that's correct.
Also I can verify that the BinTray jar for athanor is running on Linux as well as Mac. I have some more thoughts on this, but will fill you in next week.

**Comment by andrewresearch** [comment]
See also #26 - include config in Application.conf
